app:
    resource: '@AppBundle/Controller/'
    type: annotation

promotions:
    type:     rest
    resource: AppBundle\Controller\ApiPromotionController

students:
    type:     rest
    resource: AppBundle\Controller\ApiStudentController
